-- list of all students
SELECT * 
FROM STUDENT;

-- list of all trainers
SELECT *
FROM TRAINER;

-- list of all assignments
SELECT *
FROM ASSIGNMENT;

-- list of all courses
SELECT * 
FROM COURSE;

-- all the students per course
SELECT STUDENT_ID,STU_FNAME,STU_LNAME,COURSE_ID,COURSE_TITLE,private_school.course.stream,private_school.course.type,START_DATE,END_DATE
FROM STUDENT
JOIN STUDENTCOURSE ON STUDENT_ID = STU_INV_COU
JOIN COURSE ON COURSE_ID = COU_INV_STU
ORDER BY COURSE_TITLE;

-- all the trainers per course
SELECT TRAINER_ID,TRA_FNAME,TRA_LNAME,private_school.TRAINER.SUBJECT,COURSE_ID,COURSE_TITLE,private_school.course.STREAM,private_school.COURSE.TYPE,START_DATE,END_DATE
FROM TRAINER
JOIN TRAINERSCOURSE ON TRAINER_ID = TRA_INV_COU
JOIN COURSE ON COU_INV_TRA = COURSE_ID
ORDER BY COURSE_TITLE;

-- all the assignments per course
SELECT COURSE_ID,COURSE_TITLE,private_school.COURSE.STREAM,private_school.COURSE.TYPE,START_DATE,END_DATE,ASS_ID,ASS_TITLE,SUB_DATE_TIME
FROM ASSIGNMENT
JOIN ASSCOURSE ON ASS_ID = ASS_INV_COU
JOIN COURSE ON COURSE_ID = COU_INV_ASS
ORDER BY COURSE_TITLE;

-- All the assignments per course per student
SELECT STUDENT_ID,STU_FNAME,STU_LNAME,COURSE_ID,COURSE_TITLE,private_school.course.stream,private_school.course.type,START_DATE,END_DATE,ASS_ID,ASS_TITLE,SUB_DATE_TIME
FROM STUDENT
JOIN studentcourse ON STUDENT_ID = Stu_Inv_Cou
JOIN COURSE ON COU_INV_STU = COURSE_ID
JOIN asscourse ON COURSE_ID = COU_INV_ASS
JOIN ASSIGNMENT ON ASS_INV_COU = ASS_ID
ORDER BY STUDENT_ID;

-- List of All the students that belong to more than one courses
SELECT STUDENT_ID,STU_FNAME,STU_LNAME
FROM STUDENT
JOIN STUDENTCOURSE ON STUDENT_ID = STU_INV_COU
GROUP BY STUDENT_ID
HAVING COUNT(STU_INV_COU) > 1;